blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/qte77/doc-pipeline-engine/blob/main/README.md
    about: Check the documentation before opening an issue
