#!/usr/bin/env bash
# Copyright 2026 qte77
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# Download sample documents for pipeline testing and demo.
# These files are third-party content under various licenses (not Apache-2.0).
# See NOTICE and samples/SAMPLES.md for per-file licenses and attribution.
#
usage() {
  echo "Usage: $0 <--download|--manifest>"
  echo ""
  echo "  --download   Download samples + generate samples/SAMPLES.md"
  echo "  --manifest   Generate samples/SAMPLES.md only (no downloads)"
  echo ""
  echo "See NOTICE and samples/SAMPLES.md for per-file licenses."
  exit 0
}

case "${1:-}" in
  --download) MANIFEST_ONLY=false ;;
  --manifest) MANIFEST_ONLY=true ;;
  *)          usage ;;
esac

BASE="samples"
MANIFEST="$BASE/SAMPLES.md"
DIR=""
TODAY=$(date +%Y-%m-%d)

UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
MANUAL_URLS=()

# --- manifest helpers ---

manifest_init() {
  cat > "$MANIFEST" <<EOF
---
title: Sample Documents Manifest
description: Catalog of all sample documents for pipeline testing and demo
created: 2026-04-22
updated: $TODAY
urls_validated: $TODAY
license_note: >
  Files are third-party content under various licenses (not Apache-2.0).
  See NOTICE for license summaries and attribution requirements.
---

# Sample Documents

Auto-generated by \`scripts/download-samples.sh\` on $TODAY.
EOF
}

manifest_section() {
  cat >> "$MANIFEST" <<EOF

## $1

| File | Description | License | Source |
|------|-------------|---------|--------|
EOF
}

manifest_entry() {
  echo "| $1 | $2 | $3 | $4 |" >> "$MANIFEST"
}

# --- download + record ---

section() {
  DIR="$BASE/$1"
  CURRENT_SECTION="$2"
  mkdir -p "$DIR"
  echo "=== $2 ==="
  manifest_section "$1/"
}

# dl FILE URL DESCRIPTION LICENSE SOURCE_URL
dl() {
  local file="$DIR/$1" url="$2" desc="$3" license="$4" source="$5"

  # always write manifest
  manifest_entry "$1" "$desc" "$license" "$source"

  # skip download in manifest-only mode
  $MANIFEST_ONLY && return

  # skip if already downloaded
  [ -s "$file" ] && echo "  SKIP (exists): $1" && return

  echo "  $url"
  # 1. plain curl
  curl -sfL --max-time 60 -o "$file" "$url" 2>/dev/null && [ -s "$file" ] && return
  # 2. curl with browser UA
  curl -sfL --max-time 60 -A "$UA" -o "$file" "$url" 2>/dev/null && [ -s "$file" ] && return
  # 3. wget (follows more redirects, handles cookies better)
  wget -q --max-redirect=10 --content-disposition -O "$file" "$url" 2>/dev/null && [ -s "$file" ] && return
  # all failed
  rm -f "$file"
  MANUAL_URLS+=("$file  $url")
  echo "  FAILED (all methods): $1"
}


# ============================================================================
# SAMPLES — single source of truth for files, URLs, licenses, descriptions
# ============================================================================

mkdir -p "$BASE"
manifest_init


section generic "Generic (papers, reports)"
dl arxiv-attention-is-all-you-need.pdf \
  "https://arxiv.org/pdf/1706.03762" \
  "Transformer paper (Vaswani et al., 2017)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/1706.03762"
dl arxiv-bert.pdf \
  "https://arxiv.org/pdf/1810.04805" \
  "BERT (Devlin et al., 2018)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/1810.04805"
dl arxiv-resnet.pdf \
  "https://arxiv.org/pdf/1512.03385" \
  "Deep Residual Learning (He et al., 2015)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/1512.03385"
dl arxiv-dropout.pdf \
  "https://arxiv.org/pdf/1207.0580" \
  "Dropout (Srivastava et al., 2014)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/1207.0580"
dl arxiv-batch-normalization.pdf \
  "https://arxiv.org/pdf/1502.03167" \
  "Batch Normalization (Ioffe & Szegedy, 2015)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/1502.03167"
dl arxiv-adam-optimizer.pdf \
  "https://arxiv.org/pdf/1412.6980" \
  "Adam optimizer (Kingma & Ba, 2014)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/1412.6980"
dl arxiv-gan.pdf \
  "https://arxiv.org/pdf/1406.2661" \
  "GANs (Goodfellow et al., 2014)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/1406.2661"
dl arxiv-word2vec.pdf \
  "https://arxiv.org/pdf/1301.3781" \
  "Word2Vec (Mikolov et al., 2013)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/1301.3781"
dl arxiv-gpt3.pdf \
  "https://arxiv.org/pdf/2005.14165" \
  "GPT-3 (Brown et al., 2020)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/2005.14165"
dl arxiv-vit.pdf \
  "https://arxiv.org/pdf/2010.11929" \
  "Vision Transformer (Dosovitskiy et al., 2020)" \
  "arXiv non-exclusive" \
  "https://arxiv.org/abs/2010.11929"
dl arxiv-decade-deep-learning.pdf \
  "https://arxiv.org/pdf/2412.16188" \
  "Survey of 7 deep learning architectures" \
  "CC-BY 4.0" \
  "https://arxiv.org/abs/2412.16188"
dl plos-knowledge-tracing.pdf \
  "https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0330433&type=printable" \
  "LSTM+Informer student performance prediction" \
  "CC-BY 4.0" \
  "https://doi.org/10.1371/journal.pone.0330433"
dl elife-sharp-wave-ripples.pdf \
  "https://elifesciences.org/articles/97270.pdf" \
  "Sharp wave-ripples neuroscience study" \
  "CC-BY 4.0" \
  "https://elifesciences.org/articles/97270"
dl nist-sp800-63b.pdf \
  "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf" \
  "NIST Digital Identity Guidelines" \
  "US Public Domain" \
  "https://csrc.nist.gov/pubs/sp/800/63/b/upd2/final"
dl nist-sp800-53r5.pdf \
  "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf" \
  "NIST Security and Privacy Controls" \
  "US Public Domain" \
  "https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final"
dl nist-sp800-236-cyber-privacy-2024.pdf \
  "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-236.pdf" \
  "NIST Cybersecurity and Privacy FY 2024" \
  "US Public Domain" \
  "https://csrc.nist.gov/pubs/sp/800/236/final"
dl nist-sp800-171r3-cui-security.pdf \
  "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-171r3.pdf" \
  "NIST CUI Security Requirements" \
  "US Public Domain" \
  "https://csrc.nist.gov/pubs/sp/800/171/r3/final"
dl nasa-lunar-rover-assessment.pdf \
  "https://ntrs.nasa.gov/api/citations/20240014203/downloads/11-15-24%2020240014203.pdf" \
  "NASA lunar rover design assessment" \
  "US Public Domain" \
  "https://ntrs.nasa.gov/citations/20240014203"


section mech-elec-cert "Mech-Elec-Cert (datasheets, images, schematics)"
dl ti-ne555-datasheet.pdf \
  "https://www.ti.com/lit/ds/symlink/ne555.pdf" \
  "NE555 precision timer IC" \
  "TI freely redistributable" \
  "https://www.ti.com/product/NE555"
dl ti-lm317-datasheet.pdf \
  "https://www.ti.com/lit/ds/symlink/lm317.pdf" \
  "LM317 adjustable voltage regulator" \
  "TI freely redistributable" \
  "https://www.ti.com/product/LM317"
dl nasa-std-8739-soldering.pdf \
  "https://nepp.nasa.gov/docuploads/06AA01BA-FC7E-4094-AE829CE371A7B05D/NASA-STD-8739.3.pdf" \
  "NASA soldered connections workmanship standard" \
  "US Public Domain" \
  "https://nepp.nasa.gov/"
dl nist-sp800-183-iot.pdf \
  "https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-183.pdf" \
  "NIST Networks of Things architecture" \
  "US Public Domain" \
  "https://csrc.nist.gov/pubs/sp/800/183/final"
dl adafruit-multimeters-guide.pdf \
  "https://cdn-learn.adafruit.com/downloads/pdf/multimeters.pdf" \
  "Adafruit guide to using multimeters" \
  "CC-BY-SA 3.0" \
  "https://learn.adafruit.com/multimeters"
dl adafruit-arduino-leds.pdf \
  "https://cdn-learn.adafruit.com/downloads/pdf/adafruit-arduino-lesson-2-leds.pdf" \
  "Adafruit Arduino LED lesson" \
  "CC-BY-SA 3.0" \
  "https://learn.adafruit.com/adafruit-arduino-lesson-2-leds"
dl wikimedia-arduino-uno-r3.jpg \
  "https://upload.wikimedia.org/wikipedia/commons/3/38/Arduino_Uno_-_R3.jpg" \
  "Arduino Uno R3 board photo" \
  "CC-BY 2.0" \
  "https://commons.wikimedia.org/wiki/File:Arduino_Uno_-_R3.jpg"
dl wikimedia-raspberry-pi-bplus.jpg \
  "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Raspberry_Pi_B%2B_top.jpg/1280px-Raspberry_Pi_B%2B_top.jpg" \
  "Raspberry Pi B+ top-down photo" \
  "CC-BY-SA 3.0" \
  "https://commons.wikimedia.org/wiki/File:Raspberry_Pi_B%2B_top.jpg"
dl wikimedia-capacitors.jpg \
  "https://upload.wikimedia.org/wikipedia/commons/b/b9/Capacitors_%287189597135%29.jpg" \
  "Assorted capacitors close-up" \
  "CC-BY-SA 2.0" \
  "https://commons.wikimedia.org/wiki/File:Capacitors_(7189597135).jpg"
dl wikimedia-cnc-machine.jpg \
  "https://upload.wikimedia.org/wikipedia/commons/a/ac/CNC_machine.jpg" \
  "CNC woodworking machine" \
  "Public Domain" \
  "https://commons.wikimedia.org/wiki/File:CNC_machine.jpg"
dl wikimedia-stepper-motor.jpg \
  "https://upload.wikimedia.org/wikipedia/commons/c/cf/Stepper_motor.jpg" \
  "MICROCON stepper motor" \
  "CC-BY 3.0" \
  "https://commons.wikimedia.org/wiki/File:Stepper_motor.jpg"
dl wikimedia-electric-motor-diagram.png \
  "https://upload.wikimedia.org/wikipedia/commons/5/59/Electric_motor_cycle_3.png" \
  "Electric motor cycle diagram" \
  "CC-BY-SA 3.0" \
  "https://commons.wikimedia.org/wiki/File:Electric_motor_cycle_3.png"
dl wikimedia-servomotor.jpg \
  "https://commons.wikimedia.org/wiki/Special:FilePath/Servomotor.jpg" \
  "DC servomotor with gear train" \
  "CC-BY-SA 3.0" \
  "https://commons.wikimedia.org/wiki/File:Servomotor.jpg"
dl wikimedia-servo-motor-drive.png \
  "https://upload.wikimedia.org/wikipedia/commons/7/73/Servo_motor_drive.png" \
  "Servo motor drives with field bus cable" \
  "CC-BY-SA 3.0" \
  "https://commons.wikimedia.org/wiki/File:Servo_motor_drive.png"
dl wikimedia-inside-servo-motor.jpg \
  "https://upload.wikimedia.org/wikipedia/commons/9/9c/Inside_a_servo_motor.JPG" \
  "Internal view of a servo motor" \
  "CC-BY-SA 3.0" \
  "https://commons.wikimedia.org/wiki/File:Inside_a_servo_motor.JPG"
dl wikimedia-ohms-law-triangle.svg \
  "https://upload.wikimedia.org/wikipedia/commons/f/fb/Ohm%27s_law_triangle.svg" \
  "Ohm's law mnemonic triangle" \
  "Public Domain" \
  "https://commons.wikimedia.org/wiki/File:Ohm%27s_law_triangle.svg"
dl wikimedia-555-pinout.svg \
  "https://upload.wikimedia.org/wikipedia/commons/c/c7/555_Pinout.svg" \
  "555 timer IC pinout diagram" \
  "Public Domain" \
  "https://commons.wikimedia.org/wiki/File:555_Pinout.svg"
dl wikimedia-op-amp-symbol.svg \
  "https://upload.wikimedia.org/wikipedia/commons/9/97/Op-amp_symbol.svg" \
  "Op-amp schematic symbol" \
  "CC-BY-SA 3.0" \
  "https://commons.wikimedia.org/wiki/File:Op-amp_symbol.svg"
dl wikimedia-resistor-symbol.svg \
  "https://upload.wikimedia.org/wikipedia/commons/e/ee/Resistor_symbol_America.svg" \
  "US-style resistor symbol" \
  "Public Domain" \
  "https://commons.wikimedia.org/wiki/File:Resistor_symbol_America.svg"
dl wikimedia-circuit-elements.svg \
  "https://upload.wikimedia.org/wikipedia/commons/c/cb/Circuit_elements.svg" \
  "Common circuit element symbols" \
  "CC-BY-SA 3.0" \
  "https://commons.wikimedia.org/wiki/File:Circuit_elements.svg"
dl wikimedia-transformer-3d.svg \
  "https://upload.wikimedia.org/wikipedia/commons/6/64/Transformer3d_col3.svg" \
  "3D single-phase transformer" \
  "CC-BY-SA 3.0" \
  "https://commons.wikimedia.org/wiki/File:Transformer3d_col3.svg"


section contracts "Contracts (procurement, bids, tenders)"
dl gsa-sf26-award-contract.pdf \
  "https://www.gsa.gov/system/files/SF26-22.pdf" \
  "SF 26 — Award/Contract" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms/awardcontract"
dl gsa-sf33-solicitation-offer-award.pdf \
  "https://www.gsa.gov/system/files/SF33-22.pdf" \
  "SF 33 — Solicitation, Offer, and Award" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms/solicitation-offer-and-award"
dl gsa-sf1449-commercial-solicitation.pdf \
  "https://www.gsa.gov/cdnstatic/SF1449-21.pdf" \
  "SF 1449 — Commercial Products/Services" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms"
dl gsa-sf1447-solicitation-contract.pdf \
  "https://www.gsa.gov/system/files/SF1447-22.pdf" \
  "SF 1447 — Simplified acquisitions" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms"
dl gsa-sf30-amendment-modification.pdf \
  "https://www.gsa.gov/cdnstatic/SF30-16c.pdf" \
  "SF 30 — Amendment/Modification" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms"
dl gsa-sf1442-construction-solicitation.pdf \
  "https://www.gsa.gov/system/files/SF1442-22.pdf" \
  "SF 1442 — Construction solicitation" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms"
dl gsa-sf24-bid-bond.pdf \
  "https://www.gsa.gov/system/files/2024-02/SF24-23a.pdf" \
  "SF 24 — Bid Bond" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms"
dl gsa-sf25-performance-bond.pdf \
  "https://www.gsa.gov/system/files/2024-02/SF25-23a.pdf" \
  "SF 25 — Performance Bond" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms"
dl gsa-sf294-subcontracting-report.pdf \
  "https://www.gsa.gov/system/files/2025-05/SF294-21a.pdf" \
  "SF 294 — Subcontracting Report" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms"
dl uk-short-form-contract.docx \
  "https://assets.publishing.service.gov.uk/media/68aedca0969253904d155891/Short_Form_Contract_-_Word_v1.5A_2025__1_.docx" \
  "UK Cabinet Office Short Form Contract" \
  "UK OGL v3.0" \
  "https://www.gov.uk/government/publications/short-form-contract"
dl uk-grant-agreement-template.pdf \
  "https://assets.publishing.service.gov.uk/media/5e39c31ced915d091c7ca810/Grant_Contract_Agreement_Template.pdf" \
  "UK Grant Contract Agreement" \
  "UK OGL v3.0" \
  "https://www.gov.uk/government/publications"
dl uk-ppn-standard-contracts.pdf \
  "https://assets.publishing.service.gov.uk/media/64c8ffa119f562000df3c200/PPN_08_23_Using_Standard_Contracts_-_Final_Version__1_.pdf" \
  "PPN 08/23 — Using Standard Contracts" \
  "UK OGL v3.0" \
  "https://www.gov.uk/government/publications"
dl worldbank-sbd-goods.pdf \
  "https://thedocs.worldbank.org/en/doc/198281599055339370-0290022013/render/SBDProcurementofGoodsmar2013.pdf" \
  "World Bank SBD Procurement of Goods" \
  "World Bank open access" \
  "https://www.worldbank.org/en/projects-operations/products-and-services/brief/procurement-policies-and-guidance"
dl worldbank-sbd-works.pdf \
  "https://thedocs.worldbank.org/en/doc/284441487883384455-0290022017/render/SBDWORKS.pdf" \
  "World Bank SBD Procurement of Works" \
  "World Bank open access" \
  "https://www.worldbank.org/en/projects-operations/products-and-services/brief/procurement-policies-and-guidance"
dl worldbank-bid-evaluation.pdf \
  "https://documents1.worldbank.org/curated/en/995641468186255581/pdf/98848-WP-Box393178B-PUBLIC-Standard-Bidding-Evaluation-Report.pdf" \
  "World Bank Bid Evaluation Form" \
  "World Bank open access" \
  "https://documents.worldbank.org/"


section invoices "Invoices (vouchers, billing)"
dl gsa-sf1034-invoice.pdf \
  "https://www.gsa.gov/system/files/SF1034-87c.pdf" \
  "SF 1034 — Public Voucher" \
  "US Public Domain" \
  "https://www.gsa.gov/reference/forms"
dl nifc-sf1034-invoice.pdf \
  "https://gacc.nifc.gov/eacc/management_admin/incident_business/documents/sf_1034.pdf" \
  "NIFC-hosted SF 1034 voucher" \
  "US Public Domain" \
  "https://gacc.nifc.gov/"
dl gpo-billing-instructions.pdf \
  "https://www.gpo.gov/docs/default-source/vendor-files/billing-instructions.pdf" \
  "GPO vendor billing instructions" \
  "US Public Domain" \
  "https://www.gpo.gov/"
dl gpo-invoice-faq.pdf \
  "https://www.gpo.gov/docs/default-source/vendor-files/2-finance-faq-vendors.pdf" \
  "GPO invoice FAQ for vendors" \
  "US Public Domain" \
  "https://www.gpo.gov/"
dl g-invoicing-rules.pdf \
  "https://www.fiscal.treasury.gov/files/g-invoice/g-invoicing-rules-of-engagement.pdf" \
  "Treasury G-Invoicing rules" \
  "US Public Domain" \
  "https://www.fiscal.treasury.gov/"
dl archives-billing-instructions.pdf \
  "https://www.archives.gov/files/federal-register/write/conference/publishing-billing.pdf" \
  "National Archives billing instructions" \
  "US Public Domain" \
  "https://www.archives.gov/"
dl gpo-form-2511-instructions.pdf \
  "https://www.gpo.gov/docs/default-source/forms-standards-pdf-files/2511_instructions.pdf" \
  "GPO Print Order Form 2511" \
  "US Public Domain" \
  "https://www.gpo.gov/"
dl treasury-sample-invoice.pdf \
  "https://www.fiscal.treasury.gov/files/crs/sample-letters.pdf" \
  "Treasury CRS sample invoice" \
  "US Public Domain" \
  "https://www.fiscal.treasury.gov/"
dl huggingface-sample-invoice.pdf \
  "https://huggingface.co/datasets/philschmid/pdf-samples/resolve/main/invoice.pdf" \
  "Sample invoice (HuggingFace)" \
  "Apache-2.0" \
  "https://huggingface.co/datasets/philschmid/pdf-samples"


section communication "Communication (memos, letters, RFCs)"
dl omb-m24-18-ai-acquisition.pdf \
  "https://www.whitehouse.gov/wp-content/uploads/2024/10/M-24-18-AI-Acquisition-Memorandum.pdf" \
  "OMB memo M-24-18 on AI acquisition" \
  "US Public Domain" \
  "https://www.whitehouse.gov/omb/information-for-agencies/memoranda/"
dl omb-m24-10-ai-governance.pdf \
  "https://www.whitehouse.gov/wp-content/uploads/2024/03/M-24-10-Advancing-Governance-Innovation-and-Risk-Management-for-Agency-Use-of-Artificial-Intelligence.pdf" \
  "OMB memo M-24-10 on AI governance" \
  "US Public Domain" \
  "https://www.whitehouse.gov/omb/information-for-agencies/memoranda/"
dl omb-m23-07-electronic-records.pdf \
  "https://www.whitehouse.gov/wp-content/uploads/2022/12/m_23_07-m-memo-electronic-records_final.pdf" \
  "OMB memo M-23-07 on electronic records" \
  "US Public Domain" \
  "https://www.whitehouse.gov/omb/information-for-agencies/memoranda/"
dl senate-hearing-ai-transparency.pdf \
  "https://www.govinfo.gov/content/pkg/CHRG-118shrg59704/pdf/CHRG-118shrg59704.pdf" \
  "Senate hearing on AI transparency (2023)" \
  "US Public Domain" \
  "https://www.govinfo.gov/"
dl dhs-action-memo-template.pdf \
  "https://www.dhs.gov/sites/default/files/2022-03/Action%20Memo%20Template.pdf" \
  "DHS Action/Decision Memo Template" \
  "US Public Domain" \
  "https://www.dhs.gov/"
dl rfc2119-keywords.txt \
  "https://www.rfc-editor.org/rfc/rfc2119.txt" \
  "RFC 2119 — Key words for RFCs" \
  "IETF Trust (redistribution OK, no modifications)" \
  "https://www.rfc-editor.org/rfc/rfc2119"
dl rfc5321-smtp.txt \
  "https://www.rfc-editor.org/rfc/rfc5321.txt" \
  "RFC 5321 — SMTP specification" \
  "IETF Trust (redistribution OK, no modifications)" \
  "https://www.rfc-editor.org/rfc/rfc5321"
dl rfc2822-email-format.txt \
  "https://www.rfc-editor.org/rfc/rfc2822.txt" \
  "RFC 2822 — Internet Message Format" \
  "IETF Trust (redistribution OK, no modifications)" \
  "https://www.rfc-editor.org/rfc/rfc2822"
dl rfc7231-http-semantics.txt \
  "https://www.rfc-editor.org/rfc/rfc7231.txt" \
  "RFC 7231 — HTTP/1.1 Semantics" \
  "IETF Trust (redistribution OK, no modifications)" \
  "https://www.rfc-editor.org/rfc/rfc7231"
dl rfc791-ip.txt \
  "https://www.rfc-editor.org/rfc/rfc791.txt" \
  "RFC 791 — Internet Protocol" \
  "IETF Trust (redistribution OK, no modifications)" \
  "https://www.rfc-editor.org/rfc/rfc791"
dl rfc2616-http.txt \
  "https://www.rfc-editor.org/rfc/rfc2616.txt" \
  "RFC 2616 — HTTP/1.1 (original)" \
  "IETF Trust (redistribution OK, no modifications)" \
  "https://www.rfc-editor.org/rfc/rfc2616"
dl gutenberg-lincoln-letters.txt \
  "https://www.gutenberg.org/cache/epub/8110/pg8110.txt" \
  "Lincoln Letters — Civil War correspondence" \
  "Public Domain" \
  "https://www.gutenberg.org/ebooks/8110"
dl gutenberg-lincoln-speeches.txt \
  "https://www.gutenberg.org/cache/epub/14721/pg14721.txt" \
  "Speeches and Letters of Abraham Lincoln" \
  "Public Domain" \
  "https://www.gutenberg.org/ebooks/14721"
dl gutenberg-business-correspondence.txt \
  "https://www.gutenberg.org/cache/epub/7309/pg7309.txt" \
  "Business Correspondence (how to write)" \
  "Public Domain" \
  "https://www.gutenberg.org/ebooks/7309"
dl gutenberg-how-to-write-letters.txt \
  "https://www.gutenberg.org/cache/epub/22222/pg22222.txt" \
  "How to Write Letters (Crowther)" \
  "Public Domain" \
  "https://www.gutenberg.org/ebooks/22222"
dl gutenberg-austen-letters.txt \
  "https://www.gutenberg.org/ebooks/42078.txt.utf-8" \
  "Letters of Jane Austen" \
  "Public Domain" \
  "https://www.gutenberg.org/ebooks/42078"


section legal/us "Legal — US"
dl us-constitution.pdf \
  "https://www.govinfo.gov/content/pkg/CDOC-110hdoc50/pdf/CDOC-110hdoc50.pdf" \
  "US Constitution as amended" \
  "US Public Domain" \
  "https://www.govinfo.gov/"
dl us-efoia-1996.pdf \
  "https://www.govinfo.gov/content/pkg/PLAW-104publ231/pdf/PLAW-104publ231.pdf" \
  "Electronic FOIA Amendments of 1996" \
  "US Public Domain" \
  "https://www.govinfo.gov/"
dl us-open-government-act-2007.pdf \
  "https://www.govinfo.gov/content/pkg/PLAW-110publ175/pdf/PLAW-110publ175.pdf" \
  "OPEN Government Act of 2007" \
  "US Public Domain" \
  "https://www.govinfo.gov/"

section legal/uk "Legal — UK"
dl uk-data-protection-act-2018.pdf \
  "https://www.legislation.gov.uk/ukpga/2018/12/pdfs/ukpga_20180012_en.pdf" \
  "Data Protection Act 2018" \
  "UK OGL v3.0" \
  "https://www.legislation.gov.uk/ukpga/2018/12"

section legal/eu "Legal — EU"
dl eu-gdpr-2016-679.pdf \
  "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679" \
  "GDPR Regulation (EU) 2016/679" \
  "EU reuse (Decision 2011/833/EU)" \
  "https://eur-lex.europa.eu/eli/reg/2016/679/oj"
dl eu-digital-services-act-2022.pdf \
  "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32022R2065" \
  "Digital Services Act (EU) 2022/2065" \
  "EU reuse (Decision 2011/833/EU)" \
  "https://eur-lex.europa.eu/eli/reg/2022/2065/oj"
dl eu-ai-act-2024.pdf \
  "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=OJ:L_202401689" \
  "AI Act (EU) 2024/1689" \
  "EU reuse (Decision 2011/833/EU)" \
  "https://eur-lex.europa.eu/eli/reg/2024/1689/oj"

section legal/au "Legal — Australia"
dl au-privacy-act-1988.pdf \
  "https://www.legislation.gov.au/C2004A03712/2025-06-10/2025-06-10/text/original/pdf" \
  "Privacy Act 1988" \
  "CC-BY 4.0" \
  "https://www.legislation.gov.au/C2004A03712"

section legal/nz "Legal — New Zealand"
dl nz-bill-of-rights-act-1990.pdf \
  "https://www.legislation.govt.nz/act/public/1990/0109/latest/096be8ed81c84723.pdf" \
  "Bill of Rights Act 1990" \
  "CC-BY 4.0 NZ" \
  "https://www.legislation.govt.nz/act/public/1990/0109"
dl nz-privacy-act-2020.pdf \
  "https://legislation.govt.nz/act/public/2020/31/en/2020-06-30.pdf" \
  "Privacy Act 2020" \
  "CC-BY 4.0 NZ" \
  "https://www.legislation.govt.nz/act/public/2020/0031"

section legal/br "Legal — Brazil"
dl br-constituicao-1988.pdf \
  "https://www.planalto.gov.br/ccivil_03/constituicao/DOUconstituicao88.pdf" \
  "Federal Constitution 1988 (original DOU)" \
  "Public Domain (Brazilian gov)" \
  "https://www.planalto.gov.br/ccivil_03/constituicao/"
dl br-constituicao-atualizada.pdf \
  "https://www2.camara.leg.br/legin/fed/consti/1988/constituicao-1988-5-outubro-1988-322142-normaatualizada-pl.pdf" \
  "Federal Constitution (consolidated)" \
  "Public Domain (Brazilian gov)" \
  "https://www2.camara.leg.br/"


section patents "Patents (US Public Domain)"
dl us-patent-pagerank.pdf \
  "https://patentimages.storage.googleapis.com/37/a9/18/d7c46ea42c4b05/US6285999.pdf" \
  "US6285999 — Google PageRank (1998)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US6285999B1"
dl us-patent-amazon-1click.pdf \
  "https://patentimages.storage.googleapis.com/37/e6/81/3ebb1f33c41b4a/US5960411.pdf" \
  "US5960411 — Amazon 1-Click ordering (1997)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US5960411A"
dl us-patent-rsa-crypto.pdf \
  "https://patentimages.storage.googleapis.com/49/43/9c/b155bf231090f6/US4405829.pdf" \
  "US4405829 — RSA cryptographic system (1983)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US4405829A"
dl us-patent-engelbart-mouse.pdf \
  "https://patentimages.storage.googleapis.com/7d/13/7e/3fd1de4c37ed12/US3541541.pdf" \
  "US3541541 — Computer mouse (Engelbart, 1970)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US3541541A"
dl us-patent-bell-telephone.pdf \
  "https://patentimages.storage.googleapis.com/10/ab/a3/b4f5c6e5826640/US174465.pdf" \
  "US174465 — Telephone (Bell, 1876)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US174465A"
dl us-patent-edison-lightbulb.pdf \
  "https://patentimages.storage.googleapis.com/d4/9b/62/aac68f7e65536c/US223898.pdf" \
  "US223898 — Electric lamp (Edison, 1880)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US223898A"
dl us-patent-wright-flyer.pdf \
  "https://patentimages.storage.googleapis.com/1c/17/b5/e1f4968143a568/US821393.pdf" \
  "US821393 — Flying machine (Wright Brothers, 1906)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US821393A"
dl us-patent-transistor.pdf \
  "https://patentimages.storage.googleapis.com/4c/d7/98/e30fdc30f7dc7d/US2569347.pdf" \
  "US2569347 — Transistor (Shockley, 1951)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US2569347A"
dl us-patent-nuclear-reactor.pdf \
  "https://patentimages.storage.googleapis.com/25/7c/5f/96bc44e6f2cc4f/US2708656.pdf" \
  "US2708656 — Nuclear reactor (Fermi & Szilard, 1955)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US2708656A"
dl us-patent-apple-ipad-design.pdf \
  "https://patentimages.storage.googleapis.com/93/f8/c5/55edf7240a7b09/USD670286.pdf" \
  "USD670286 — iPad design patent (Apple, 2012)" \
  "US Public Domain" \
  "https://patents.google.com/patent/USD670286S1"
dl us-patent-swing-method.pdf \
  "https://patentimages.storage.googleapis.com/35/cc/ad/d84ed0bb6e955e/US6368227.pdf" \
  "US6368227 — Method of swinging on a swing (2002)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US6368227B1"
dl us-patent-drm-rights.pdf \
  "https://patentimages.storage.googleapis.com/dd/b4/f8/b19b63f8ad6041/US7069451.pdf" \
  "US7069451 — Digital rights management (2006)" \
  "US Public Domain" \
  "https://patents.google.com/patent/US7069451B1"


# ============================================================================
# Summary
# ============================================================================

echo ""
echo "=== Done ==="
echo "Manifest: $MANIFEST"
if $MANIFEST_ONLY; then
  echo "Manifest-only mode — no downloads attempted."
else
  total=$(find "$BASE" -type f -not -name "*.md" | wc -l)
  echo "Total files: $total"
  if [ ${#MANUAL_URLS[@]} -gt 0 ]; then
    echo ""
    echo "Failed (download manually in browser):"
    for entry in "${MANUAL_URLS[@]}"; do
      echo "  $entry"
    done
  else
    echo "All downloads OK"
  fi
fi
