#!/usr/bin/env python3
# Copyright 2026 qte77
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
"""Generate `docs/contracts.md` from the Pydantic model registry.

Walks `doc_pipeline_engine.models.REGISTRY` and emits one markdown
section per model: docstring summary, JSON Schema dump (fenced
```json), and a prose field table sourced from each
`Field(description=...)` payload.

Output is committed to `docs/contracts.md` so:
- GitHub blob view + mkdocs site both render the contracts reference,
- external evaluators (Anthropic SDK, CC CLI/SDK) read the file to
  structurally match the pipeline output.

Run via `make docs_contracts`. The Makefile target diffs the
regenerated output against the committed file; a non-zero diff
fails the gate.
"""
from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel

from doc_pipeline_engine.models import REGISTRY

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "contracts.md"


def _render_field_table(model: type[BaseModel]) -> str:
    """One row per field with name + type + description."""
    rows = ["| Field | Required | Description |", "| --- | --- | --- |"]
    for field_name, field_info in model.model_fields.items():
        required = "yes" if field_info.is_required() else "no"
        description = (field_info.description or "").replace("|", "\\|")
        rows.append(f"| `{field_name}` | {required} | {description} |")
    return "\n".join(rows)


def _render_model(name: str, model: type[BaseModel]) -> str:
    docstring = (model.__doc__ or "").strip().splitlines()[0] if model.__doc__ else ""
    schema = json.dumps(model.model_json_schema(), indent=2, sort_keys=True)
    return (
        f"## {name}\n\n"
        f"{docstring}\n\n"
        f"### Fields\n\n"
        f"{_render_field_table(model)}\n\n"
        f"### JSON Schema\n\n"
        f"```json\n{schema}\n```\n"
    )


def render() -> str:
    """Render the full contracts.md content."""
    header = (
        "---\n"
        "title: Pydantic contract reference\n"
        "purpose: Auto-generated reference for the 10 stage contracts; "
        "consumed by external evaluators to structurally match pipeline output\n"
        "created: 2026-04-27\n"
        "updated: 2026-04-27\n"
        "validated_links: 2026-04-27\n"
        "category: technical\n"
        "---\n\n"
        "Generated by `scripts/gen_contracts_md.py` from "
        "`src/doc_pipeline_engine/models/`. Do not edit by hand; "
        "regenerate via `make docs_contracts`. This file is excluded from "
        "markdown lint via `.markdownlint-cli2.jsonc` — duplicate "
        "`## Fields` / `## JSON Schema` headings + table-pipe spacing "
        "are expected for the auto-generated artifact.\n\n"
    )
    sections = "\n".join(_render_model(name, REGISTRY[name]) for name in sorted(REGISTRY))
    return header + sections


def main() -> int:
    OUTPUT_PATH.write_text(render())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
